import { Sparkles, Globe, Clock } from "lucide-react";

interface ReportFooterProps {
  timezone?: string;
}

export function ReportFooter({ timezone = "America/New_York" }: ReportFooterProps) {
  const now = new Date();
  const formattedTime = now.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });

  // Format timezone for display
  const tzDisplay = timezone.replace("_", " ").split("/").pop() || timezone;

  return (
    <footer className="mt-12 border-t border-border/50 bg-muted/20 px-6 py-4">
      <div className="flex flex-wrap items-center justify-between gap-4 text-xs text-muted-foreground">
        {/* Left: Branding */}
        <div className="flex items-center gap-1.5">
          <Sparkles className="h-3.5 w-3.5" />
          <span>Generated by <span className="font-medium">Fieldra</span></span>
        </div>

        {/* Right: Metadata */}
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-1.5">
            <Globe className="h-3.5 w-3.5" />
            <span>{tzDisplay} (site local)</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Clock className="h-3.5 w-3.5" />
            <span>Report generated {formattedTime}</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
