import { FileText, MapPin, Calendar, Clock, Sparkles } from "lucide-react";
import { JobInfo, ShiftInfo } from "@/types/reports";

interface ReportHeaderProps {
  job: JobInfo;
  shift: ShiftInfo;
  reportDate: Date;
}

export function ReportHeader({ job, shift, reportDate }: ReportHeaderProps) {
  const formattedDate = reportDate.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="bg-primary text-primary-foreground px-6 py-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        {/* Left: Title and Site Info */}
        <div>
          <div className="flex items-center gap-2 mb-2">
            <FileText className="h-5 w-5" />
            <h1 className="text-xl font-bold tracking-tight">Daily Progress Report</h1>
          </div>
          <div className="space-y-1.5">
            <p className="text-lg font-semibold text-primary-foreground/95">{job.name}</p>
            <div className="flex items-center gap-2 text-sm text-primary-foreground/75">
              <MapPin className="h-3.5 w-3.5" />
              <span>{job.address}</span>
            </div>
          </div>
        </div>

        {/* Right: Date and Shift Info */}
        <div className="flex flex-col items-start lg:items-end gap-2">
          <div className="flex items-center gap-2 text-sm">
            <Calendar className="h-4 w-4" />
            <span className="font-medium">{formattedDate}</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-primary-foreground/75">
            <Clock className="h-3.5 w-3.5" />
            <span>
              {shift.shiftType} Shift • {shift.startTime} – {shift.endTime} • {shift.workersAssigned} workers
            </span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-primary-foreground/60 mt-1">
            <Sparkles className="h-3 w-3" />
            <span>Generated by Fieldra</span>
          </div>
        </div>
      </div>
    </div>
  );
}
